### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by gdennie**
It is important to provide a contextualize sample. Ideally, all the examples should occur in context to reduce the mental load of learning. It takes more time to write, though a template approach would suffice; however, it will save hundreds of people hours of corroborative research (1000 people * 2 hours = 2000 people hours = 57 working days :)

### CODE REVIEW

**Comment by mFingers** [comment]
At this point in the documentation, it would be nice to see a fully runnable example that points out the minimum necessary to get up and running.  Your example does that.  Your example reminded me of another "barebones" example on the [Defining Resources](http://docs.freya.io/en/latest/machine/resources.html#syntax) page.  For continuity's sake (and to ease digestion of the material), it would be nice if all the examples/snippets throughout the documentation built on the same base.

I think there may be a slight philosophical difference between this example and the Defining Resources example.  This example shows the modification of the owin environment, while the other example does not.  I think the "sensible defaults" theme of web machine is important, and this example counters that.  But that's just my take - and I am by no means an expert on WebMachine or Freya.  It would be better to hear what @kolektiv or @panesofglass have to say about that.

I took the existing example and modified it so that it is runnable, like you suggest.

I also think a note about what dependencies are involved would be helpful:
```
Install-Package Freya
Install-Package Microsoft.Owin.SelfHost
```

Here's the full example, then:
```
module HelloWorldWebSite

open Arachne.Http
open Freya.Core
open Freya.Machine
open Freya.Machine.Extensions.Http
open Microsoft.Owin.Hosting
open System

// Properties

let mediaTypes =
    freya {
        return [ MediaType.Text ] }

let methods =
    freya {
        return [ GET ] }

// Decisions

let available =
    freya {
        return true }

// Handlers

let content _ =
    freya {
        return {
            Description =
              { Charset = Some Charset.Utf8
                Encodings = None
                MediaType = Some MediaType.Text
                Languages = None }
            Data = "Hello World!"B } }

// Resource

let helloWorld =
    freyaMachine {
        using http
        mediaTypesSupported (freya { return [ MediaType.Text ] })
        methodsSupported methods
        serviceAvailable available
        handleOk content } |> FreyaMachine.toPipeline

type Exercise() =
    member __.Configuration() =
        OwinAppFunc.ofFreya helloWorld

[<EntryPoint>]
let main _ =
    let url = "http://localhost:8080"
    let _ = WebApp.Start<Exercise> (url)
    Console.WriteLine("Serving site at " + url)
    Console.WriteLine("Press ENTER to cancel")
    let _ = Console.ReadLine ()
    0
```

**Comment by panesofglass** [comment]
Thank you! I've been slowly working on just this sort of thing, but I'm happy to take your samples. I agree with you, @mFingers about keeping a consistent theme for building up a sample app for most things. I imagine we could spin off a few side pages for exceptional issues, too.

**Comment by gdennie** [comment]
Presently I am getting the following error when this Console project is configured and executed. The indication is that there is an incompatibility between (x86, x64, and AnyCpu) with a library supporting a value in the `HelloWorldWebSite` module.

    System.TypeInitializationException was unhandled
    Message: An unhandled exception of type 'System.TypeInitializationException' occurred in Unknown Module.
    Additional information: The type initializer for 'HelloWorldWebSite' threw an exception.

**Comment by mFingers** [comment]
I just tried this using Visual Studio 2015 CE.

1. File, New Project (F# Console Application)
1. Copy and Pasted the code
1. Used Package Manager Console to add the two dependencies
1. F5, navigate to localhost:8080

The project properties are all the VS defaults:  F# 4.0, targeting .NET 4.5.2, and "Any CPU"

What environment are you using?

**Comment by gdennie** [comment]
It Works now.

I had install the packages with the GUI version of VS2015 Nuget Package
Manager. I believe it's default package selection criteria is perhaps
different.

Incidentally, my platform is Win8.1. While it is nolonger important, my
target framework in this last test was 4.6 using F# 4.0

Thanks.

**Pull request merged**
